services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=language_learning_app
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../api:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    command: sh -c "sleep 10 && npm run migration:run && npm run start:dev"

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=language_learning_app
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8088:80"
    depends_on:
      - db
    restart: always

volumes:
  mysql_data:
